"""Add profile customization fields

Revision ID: 2b871737a6b4
Revises: 
Create Date: 2025-08-12 22:44:14.806721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b871737a6b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dislikes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preferred_traits', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=150), nullable=True))
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('budget')
        batch_op.drop_column('preferred_traits')
        batch_op.drop_column('dislikes')
        batch_op.drop_column('likes')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
